---
# - name: remove existing aws folder
#   ansible.builtin.file:
#     state: absent
#     path: "/home/{{ target_user }}/tmp/aws"
#   tags: aws_install
#   become: true
# https://books.stuartherbert.com/putting-ansible-to-work/building-software-from-source.html
