---
target_user: snarasim
public_key: /home/snarasim/.ssh/id_rsa.pub
repo_directory: code
user_home: /home/snarasim
root_user: root
root_user_key: /root/.ssh/id_rsa.pub
root_user_home: /root
git_install_path: /usr
git_user_email: snarasim123@gmail.com

