---
user: snarasim
public_key: ~/.ssh/id_rsa.pub
repo_directory: code
user_home: /home/snarasim
# repos:
# dotfiles_repo: snarasim/dotfiles
# dotfiles_branch: master
# dotfiles_command: bash install.sh

