---
- name: Create bashfiles directory if it does not exist
  ansible.builtin.file:
    path: "{{ user_home }}/bashfiles"
    state: directory
    mode: '0755'
  tags: folders

- name: Create bin directory if it does not exist
  ansible.builtin.file:
    path: "{{ user_home }}/bin"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
  tags: folders
  become: true

- name: Create temp directory if it does not exist
  ansible.builtin.file:
    path: "{{ user_home }}/tmp"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0777'
  tags: folders
  become: true