---
- name: Create root bashfiles directory if it does not exist
  ansible.builtin.file:
    path: "{{ root_user_home }}/bashfiles"
    state: directory
    mode: '0755'
  tags: folders
  become: true

- name: Create root bin directory if it does not exist
  ansible.builtin.file:
    path: "{{ root_user_home }}/bin"
    state: directory
    owner: "{{ root_user }}"
    group: "{{ root_user }}"
    mode: '0755'
  tags: folders
  become: true

- name: Create root temp directory if it does not exist
  ansible.builtin.file:
    path: "{{ root_user_home }}/tmp"
    state: directory
    owner: "{{ root_user }}"
    group: "{{ root_user }}"
    mode: '0755'
  tags: folders
  become: true